<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1960396123993710"
     crossorigin="anonymous"></script>
<!-- 侧边栏广告 -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-1960396123993710"
     data-ad-slot="8727851886"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>